- name: "Make manage.py executable"
  file:
    path: "{{ dest }}/manage.py"
    mode: "+x"
- name: "Run migrations"
  django_manage:
    command: migrate
    app_path: "{{ dest }}"
    virtualenv: "{{ venv_path }}"
  become: yes
  become_user: "{{ owner }}"
- name: "Collect static files"
  django_manage:
    command: collectstatic
    app_path: "{{ dest }}"
    virtualenv: "{{ venv_path }}"
  become: yes
  become_user: "{{ owner }}"
