- name: "Run tests"
  django_manage:
    command: "{{ django_test_command }}"
    app_path: "{{ dest }}"
    virtualenv: "{{ venv_path }}"
  become: yes
  become_user: "{{ owner }}"
  register: result
  when:
    - script is not defined
    - framework == "django"
- name: "Run tests"
  shell: "{{ venv_path }}/bin/{{ script }}"
  when: script is defined
